"""为所有场景生成 20 条示例对话，保存到 chat_records 目录。"""
import json
from pathlib import Path

CHAT_DIR = Path(__file__).resolve().parent.parent / "data" / "chat_records"
CHAT_DIR.mkdir(parents=True, exist_ok=True)

# 每个场景的对话内容，role 为 assistant 和 user 交替，共 20 条
dialogues = {
    "free_talk": [
        {"role": "assistant", "content": "Hi there! Feel free to talk about anything you like, I'm here to chat in English!"},
        {"role": "user", "content": "Hi! How's your day going?"},
        {"role": "assistant", "content": "It's going great, thanks for asking! What about you? Anything interesting happen today?"},
        {"role": "user", "content": "Not much, just went for a walk in the park. The weather was really nice."},
        {"role": "assistant", "content": "That sounds lovely! What's your favorite thing to do when the weather is nice like this?"},
        {"role": "user", "content": "I enjoy outdoor activities like cycling and hiking. Do you like those?"},
        {"role": "assistant", "content": "Absolutely! Hiking is amazing, especially when you reach the top and see the view. Have you hiked anywhere interesting lately?"},
        {"role": "user", "content": "Yes, I went hiking last weekend in the mountains nearby. It was tiring but totally worth it."},
        {"role": "assistant", "content": "I bet the fresh air and scenery made it all worthwhile. Do you usually go alone or with friends?"},
        {"role": "user", "content": "I prefer going with friends. It's more fun and safer too. What kind of music do you like?"},
        {"role": "assistant", "content": "I enjoy a bit of everything! Pop, rock, jazz, you name it. Lately I've been listening to some lo-fi music while working. Do you have a favorite genre?"},
        {"role": "user", "content": "I love rock music. My favorite band is Imagine Dragons. Have you heard of them?"},
        {"role": "assistant", "content": "Of course! 'Believer' and 'Radioactive' are absolute classics. You've got great taste! Have you ever been to one of their concerts?"},
        {"role": "user", "content": "Not yet, but I'd love to go someday. Concerts seem so energetic and fun."},
        {"role": "assistant", "content": "They really are! The atmosphere is electric. So, do you play any musical instruments yourself?"},
        {"role": "user", "content": "I'm learning to play the guitar. It's challenging but really rewarding."},
        {"role": "assistant", "content": "That's awesome! How long have you been playing? I hear the first few months are the hardest."},
        {"role": "user", "content": "About six months now. My fingers don't hurt as much anymore, so that's progress!"},
        {"role": "assistant", "content": "Definitely progress! Keep at it and you'll be playing your favorite songs in no time. Well, it's been great chatting with you!"},
        {"role": "user", "content": "Thanks! I enjoyed our conversation. Have a great day!"},
    ],
    "restaurant": [
        {"role": "assistant", "content": "Hello! Welcome. What would you like to order?"},
        {"role": "user", "content": "Hi! Can I see the menu, please?"},
        {"role": "assistant", "content": "Of course! Here's our menu. Today's special is grilled salmon with lemon butter sauce. Would you like a moment to look it over?"},
        {"role": "user", "content": "The grilled salmon sounds great! What sides does it come with?"},
        {"role": "assistant", "content": "It comes with your choice of mashed potatoes, steamed vegetables, or a side salad. The mashed potatoes are our most popular choice."},
        {"role": "user", "content": "I'll go with the mashed potatoes then. Also, can I get a glass of water?"},
        {"role": "assistant", "content": "Great choice! One grilled salmon with mashed potatoes and a glass of water. Would you like to start with any appetizers?"},
        {"role": "user", "content": "Yes, I'd like the Caesar salad as a starter, please."},
        {"role": "assistant", "content": "A Caesar salad to start, perfect. Would you like any dressing on the side, or the classic Caesar dressing?"},
        {"role": "user", "content": "Classic Caesar dressing is fine. How long will the food take?"},
        {"role": "assistant", "content": "The salad will be out in about 5 minutes, and the main course should take around 15-20 minutes. Can I get you anything else while you wait?"},
        {"role": "user", "content": "No, that's all for now. Thank you!"},
        {"role": "assistant", "content": "You're welcome! I'll put your order in right away. Enjoy your meal!"},
        {"role": "user", "content": "Excuse me, could I get some more water please?"},
        {"role": "assistant", "content": "Absolutely! I'll refill your glass right away. Is everything tasting good so far?"},
        {"role": "user", "content": "Yes, the salmon is delicious! Please compliment the chef."},
        {"role": "assistant", "content": "I'll definitely pass that along! The chef always appreciates hearing that. Would you like to see the dessert menu?"},
        {"role": "user", "content": "Sure! What desserts do you recommend?"},
        {"role": "assistant", "content": "Our chocolate lava cake is to die for, and the tiramisu is also very popular. Both are made fresh daily."},
        {"role": "user", "content": "I'll take the chocolate lava cake, and the bill please."},
    ],
    "interview": [
        {"role": "assistant", "content": "Hello. Please introduce yourself."},
        {"role": "user", "content": "Hello, my name is Li Wei. I recently graduated with a degree in Computer Science. I'm excited to be interviewing for this position today."},
        {"role": "assistant", "content": "Nice to meet you, Li Wei. Can you tell me about your previous work experience or any projects you've worked on?"},
        {"role": "user", "content": "During university, I completed an internship at a tech company where I worked on web application development. I built a customer management system using React and Python."},
        {"role": "assistant", "content": "That sounds interesting. What was the most challenging part of that project, and how did you overcome it?"},
        {"role": "user", "content": "The biggest challenge was optimizing database queries. The system became slow with large amounts of data, so I learned about indexing and query optimization to fix it."},
        {"role": "assistant", "content": "Great problem-solving approach! What are your greatest strengths as a developer?"},
        {"role": "user", "content": "I'm very detail-oriented and I enjoy debugging complex problems. I'm also a fast learner and always eager to pick up new technologies."},
        {"role": "assistant", "content": "And what would you say is your biggest weakness?"},
        {"role": "user", "content": "I sometimes spend too much time perfecting small details. I'm learning to balance quality with efficiency and prioritize what truly matters."},
        {"role": "assistant", "content": "That's a very honest answer. Where do you see yourself in five years?"},
        {"role": "user", "content": "I see myself growing into a senior developer role, leading projects, and mentoring junior team members. I want to keep learning and making meaningful contributions."},
        {"role": "assistant", "content": "Why did you apply to our company specifically?"},
        {"role": "user", "content": "I admire your company's innovative products and collaborative culture. I believe my skills in full-stack development would allow me to contribute meaningfully to your team."},
        {"role": "assistant", "content": "How do you handle tight deadlines and pressure?"},
        {"role": "user", "content": "I stay organized by breaking large tasks into smaller milestones and communicating regularly with my team. Staying calm and focused helps me deliver quality work under pressure."},
        {"role": "assistant", "content": "What salary range are you expecting for this position?"},
        {"role": "user", "content": "Based on my research and experience level, I'm looking for something in the range of the industry standard for this role. I'm also open to discussing the full compensation package."},
        {"role": "assistant", "content": "Do you have any questions for me about the role or the company?"},
        {"role": "user", "content": "Yes, I'd love to know more about the team I'd be working with and what a typical day looks like in this position."},
    ],
    "hotel": [
        {"role": "assistant", "content": "Welcome. Do you have a reservation?"},
        {"role": "user", "content": "Yes, I made a reservation under the name Li Wei. It should be for three nights starting today."},
        {"role": "assistant", "content": "Let me look that up... Yes, I've found your reservation. A deluxe room with a king-size bed for three nights. Is that correct?"},
        {"role": "user", "content": "That's right. Does the room have a city view?"},
        {"role": "assistant", "content": "Yes, your room is on the 12th floor with a beautiful city view. Check-in time is 2 PM and check-out is 11 AM. Would you like to check in now?"},
        {"role": "user", "content": "Yes, please. I've had a long flight and I'd love to get settled in."},
        {"role": "assistant", "content": "Of course. May I see your ID or passport, and a credit card for the deposit?"},
        {"role": "user", "content": "Here's my passport and credit card."},
        {"role": "assistant", "content": "Thank you. The deposit is $200, which will be refunded upon check-out. Here's your key card for room 1208. The elevators are to your right."},
        {"role": "user", "content": "Thank you. What time is breakfast served?"},
        {"role": "assistant", "content": "Breakfast is served from 6:30 AM to 10:00 AM in the restaurant on the second floor. It's included with your room, so just show your key card."},
        {"role": "user", "content": "Great. Is there a gym in the hotel?"},
        {"role": "assistant", "content": "Yes, the fitness center is on the 15th floor and is open 24 hours. We also have a swimming pool that's open from 7 AM to 9 PM."},
        {"role": "user", "content": "Perfect! Could you also arrange a wake-up call for 7 AM tomorrow?"},
        {"role": "assistant", "content": "Certainly! I've scheduled a wake-up call for 7 AM. Is there anything else I can help you with?"},
        {"role": "user", "content": "One more thing — can you recommend any good restaurants nearby?"},
        {"role": "assistant", "content": "There are several excellent restaurants within walking distance. There's an Italian place two blocks away, and a very popular local seafood restaurant around the corner."},
        {"role": "user", "content": "The seafood place sounds perfect. Do I need a reservation?"},
        {"role": "assistant", "content": "I'd recommend making one. Would you like me to call and reserve a table for you this evening?"},
        {"role": "user", "content": "Yes, that would be wonderful! Around 7 PM please."},
    ],
    "home_life": [
        {"role": "assistant", "content": "Hey! What's something you usually do at home? I'd love to chat about daily life!"},
        {"role": "user", "content": "Hey! On weekends I usually cook breakfast for my family. It's kind of our little tradition."},
        {"role": "assistant", "content": "That's a really sweet tradition! What's your go-to breakfast to make for everyone?"},
        {"role": "user", "content": "I make pretty good pancakes with fresh fruit on top. Sometimes I'll do scrambled eggs and toast too."},
        {"role": "assistant", "content": "Yum! Homemade pancakes sound amazing. Do you have any secret ingredients that make them special?"},
        {"role": "user", "content": "I add a little vanilla extract and cinnamon to the batter. It makes a big difference!"},
        {"role": "assistant", "content": "I'll have to try that next time! So besides cooking, what else do you enjoy doing around the house?"},
        {"role": "user", "content": "I like binge-watching shows on Netflix. Right now I'm watching a crime drama series. It's really addictive."},
        {"role": "assistant", "content": "Oh, which one? I'm always looking for new shows to watch. Is it one of those that keeps you up way too late?"},
        {"role": "user", "content": "It's called 'Mindhunter.' And yes, I stayed up until 2 AM watching it last night. No regrets though!"},
        {"role": "assistant", "content": "Haha, I've been there! The 'just one more episode' trap is real. Do you usually watch alone or with family?"},
        {"role": "user", "content": "Usually with my roommate. We make popcorn and turn it into a mini movie night."},
        {"role": "assistant", "content": "That sounds so cozy! What about chores? Do you have a cleaning routine or are you more of a 'clean when it gets messy' kind of person?"},
        {"role": "user", "content": "I try to do a little cleaning every day so it doesn't pile up. But laundry... laundry is my enemy."},
        {"role": "assistant", "content": "Laundry is everyone's enemy! The folding part especially. Do you have any houseplants or pets at home?"},
        {"role": "user", "content": "I have a small cat named Momo. She's orange and very lazy. She sleeps about 20 hours a day."},
        {"role": "assistant", "content": "Momo sounds like she's living the dream life! Cats really know how to relax. Does she have any funny habits?"},
        {"role": "user", "content": "She loves sitting in cardboard boxes, even tiny ones she barely fits in. It's hilarious to watch."},
        {"role": "assistant", "content": "Classic cat behavior! Well, enjoy your next pancake breakfast and give Momo a scratch behind the ears for me!"},
        {"role": "user", "content": "Will do! Thanks for the nice chat!"},
    ],
    "directions": [
        {"role": "assistant", "content": "Hi there! Need help finding a place or asking for directions?"},
        {"role": "user", "content": "Yes, excuse me! I'm trying to get to the art museum. Is it far from here?"},
        {"role": "assistant", "content": "The art museum is about a 15-minute walk from here. Just go straight down this street for three blocks, then turn left at the traffic light."},
        {"role": "user", "content": "Three blocks straight, then left at the light. Got it. Is there a landmark I can look for?"},
        {"role": "assistant", "content": "Yes, you'll see a big fountain in the square after you turn left. The museum is the large white building right behind it. You can't miss it."},
        {"role": "user", "content": "That's helpful, thank you! Is there a bus that goes there as well?"},
        {"role": "assistant", "content": "Yes, you can take bus number 22 or 35 from the stop across the street. It's only two stops. The fare is $2.50."},
        {"role": "user", "content": "I think I'll walk since the weather is nice. Are there any good cafes near the museum?"},
        {"role": "assistant", "content": "There's a lovely cafe called 'Artistic Brew' right next to the museum. They have great coffee and sandwiches. Perfect for after your visit."},
        {"role": "user", "content": "Sounds great! By the way, how do I get to the train station from the museum?"},
        {"role": "assistant", "content": "From the museum, walk east for about 5 minutes to Central Avenue. The train station is the big brick building on your right. You'll see the clock tower."},
        {"role": "user", "content": "East... so that's the direction the sun rises, right?"},
        {"role": "assistant", "content": "Exactly! If it's morning, just walk towards the sun. Or you can follow the signs that say 'Central Station' — there are plenty along the way."},
        {"role": "user", "content": "Perfect. And one more question — where's the nearest restroom?"},
        {"role": "assistant", "content": "There's a public restroom in the shopping mall across the street, on the ground floor next to the information desk."},
        {"role": "user", "content": "Thank you so much! You've been really helpful."},
        {"role": "assistant", "content": "You're very welcome! Enjoy the museum and have a wonderful day!"},
        {"role": "user", "content": "Wait, one last thing — is the museum free on Sundays?"},
        {"role": "assistant", "content": "Yes, the museum has free admission every Sunday. It's open from 10 AM to 5 PM. It can get quite busy though, so go early if you can."},
        {"role": "user", "content": "Great tip! I'll plan to go Sunday morning then. Thanks again!"},
    ],
    "shopping": [
        {"role": "assistant", "content": "Welcome! Looking for something specific today, or just browsing?"},
        {"role": "user", "content": "Hi! I'm looking for a winter coat. Something warm but not too heavy."},
        {"role": "assistant", "content": "You've come to the right place! Our winter collection just arrived. What color were you thinking of?"},
        {"role": "user", "content": "Probably black or dark blue. Something that goes with everything."},
        {"role": "assistant", "content": "Great choice, those are very versatile colors. Let me show you this dark blue down jacket. It's lightweight but very warm, and it's water-resistant too."},
        {"role": "user", "content": "That looks nice! Can I try it on? I usually wear a medium."},
        {"role": "assistant", "content": "Of course! Here's a medium. The fitting rooms are right at the back. Take your time."},
        {"role": "user", "content": "It fits well, but the sleeves are a bit long. Do you have this in a small size?"},
        {"role": "assistant", "content": "Let me check... Yes, we have a small in the same color. Here you go. Try this one on."},
        {"role": "user", "content": "This one is perfect! How much is it?"},
        {"role": "assistant", "content": "That coat is $180, but we're having a 20% off sale on all winter items this week. So it would be $144."},
        {"role": "user", "content": "$144 with the discount? That's a good deal. Can I also look at some scarves?"},
        {"role": "assistant", "content": "Absolutely! Our scarves are right over here. We have wool, cashmere, and fleece options. The grey cashmere one would match the coat perfectly."},
        {"role": "user", "content": "The cashmere scarf is so soft! How much is it?"},
        {"role": "assistant", "content": "That scarf is $45. If you buy both the coat and the scarf, I can give you an extra 10% off the scarf."},
        {"role": "user", "content": "Okay, I'll take both! Do you accept mobile payments?"},
        {"role": "assistant", "content": "Yes, we accept all major mobile payment methods and credit cards. I'll ring you up at the counter."},
        {"role": "user", "content": "Great. Can I get a gift receipt for these, just in case?"},
        {"role": "assistant", "content": "Of course! Your total comes to $184.50 with the discounts. Would you like a bag, or do you have your own?"},
        {"role": "user", "content": "A bag would be great, thanks! You've been really helpful."},
    ],
    "medical": [
        {"role": "assistant", "content": "Hello. I'm here to help you practice talking to a doctor. What's on your mind?"},
        {"role": "user", "content": "Hi doctor. I've been having a really bad headache for the past three days. It won't go away."},
        {"role": "assistant", "content": "I'm sorry to hear that. Can you describe the pain? Is it a sharp pain or more of a dull, throbbing sensation?"},
        {"role": "user", "content": "It's more of a throbbing pain, mostly on one side of my head. It gets worse when I move around."},
        {"role": "assistant", "content": "I see. Have you taken any medication for it, like ibuprofen or acetaminophen?"},
        {"role": "user", "content": "I took some ibuprofen yesterday but it only helped for a couple of hours. The pain came back after that."},
        {"role": "assistant", "content": "Okay. Have you experienced any other symptoms? Nausea, sensitivity to light, or changes in your vision?"},
        {"role": "user", "content": "Yes, bright lights really bother me, and I felt a bit nauseous this morning. I didn't actually get sick though."},
        {"role": "assistant", "content": "Those symptoms sound like a migraine. Have you had similar headaches before?"},
        {"role": "user", "content": "I had something similar about two months ago, but it wasn't this bad. It went away after a day."},
        {"role": "assistant", "content": "I understand. Have you been under a lot of stress lately, or has your sleep schedule changed?"},
        {"role": "user", "content": "Actually, I've been working late for the past week and sleeping about five hours a night. Could that be related?"},
        {"role": "assistant", "content": "Absolutely. Stress and lack of sleep are common migraine triggers. I'd recommend getting more rest, staying hydrated, and avoiding bright screens before bed."},
        {"role": "user", "content": "I'll try that. Is there any medicine you can prescribe that would work better than ibuprofen?"},
        {"role": "assistant", "content": "I can prescribe a mild migraine medication. But I'd also like you to keep a headache diary — note when they happen, what you ate, and how much you slept."},
        {"role": "user", "content": "A headache diary? That's a good idea. How long should I keep track?"},
        {"role": "assistant", "content": "At least two weeks. If the migraines continue or get worse, come back and we'll look into further tests."},
        {"role": "user", "content": "Thank you, doctor. I'll pick up the prescription and start the diary today."},
        {"role": "assistant", "content": "You're welcome. And try to get at least seven hours of sleep tonight — it really does make a big difference."},
        {"role": "user", "content": "I will. Thanks for your help!"},
    ],
    "campus": [
        {"role": "assistant", "content": "Hi! Let's chat about school life, classes, or anything related to campus!"},
        {"role": "user", "content": "Hey! I'm so stressed about the upcoming exams. I have three of them next week."},
        {"role": "assistant", "content": "Three exams in one week? That's tough! Which subjects are you most worried about?"},
        {"role": "user", "content": "Definitely calculus. I've been struggling with integrals. No matter how much I practice, I keep making mistakes."},
        {"role": "assistant", "content": "Integrals can be tricky! Have you tried going to the math tutoring center? They have free drop-in sessions every afternoon."},
        {"role": "user", "content": "Really? I didn't know about that. Where is the tutoring center?"},
        {"role": "assistant", "content": "It's in the library building, room 204. They're open from 2 PM to 6 PM on weekdays. The tutors there are really patient."},
        {"role": "user", "content": "That's great to know! I'll definitely check it out. How are your classes going?"},
        {"role": "assistant", "content": "Pretty good! My literature class is fascinating. We're reading Shakespeare right now. But the essay deadlines are piling up."},
        {"role": "user", "content": "Oh, I hate essays. How long does your Shakespeare essay need to be?"},
        {"role": "assistant", "content": "2,000 words, due next Friday. I've only written about 500 so far. Procrastination is my biggest enemy!"},
        {"role": "user", "content": "I'm the same way! Maybe we could study together at the library this weekend and keep each other accountable?"},
        {"role": "assistant", "content": "That's a brilliant idea! I work much better when someone else is studying nearby. Saturday afternoon?"},
        {"role": "user", "content": "Saturday works for me. Let's meet at the library entrance at 1 PM. Don't be late!"},
        {"role": "assistant", "content": "Deal! By the way, did you sign up for the spring club fair? There are so many interesting clubs this semester."},
        {"role": "user", "content": "Not yet. What clubs are available?"},
        {"role": "assistant", "content": "There's a photography club, a debate team, a coding club, and even a hiking club. I'm thinking of joining the photography one."},
        {"role": "user", "content": "The coding club sounds perfect for me! Where can I sign up?"},
        {"role": "assistant", "content": "You can sign up online on the student portal, or there's a booth at the student center until Friday."},
        {"role": "user", "content": "Awesome, thanks for letting me know! See you Saturday at the library."},
    ],
    "social": [
        {"role": "assistant", "content": "Hey! Let's practice casual small talk, like greeting people or chatting about your day!"},
        {"role": "user", "content": "Hey! Long time no see! How have you been?"},
        {"role": "assistant", "content": "I know, right? I've been really good! Work has been keeping me busy, but can't complain. What about you? You look great!"},
        {"role": "user", "content": "Thanks! I've been doing well. I started a new hobby recently — I'm learning photography."},
        {"role": "assistant", "content": "No way! That's awesome! What kind of photos do you like taking? Landscapes, portraits, street photography?"},
        {"role": "user", "content": "Mostly street photography. I love capturing everyday moments that people usually overlook."},
        {"role": "assistant", "content": "That's beautiful. You'll have to show me some of your work sometime! Did you get a fancy camera for it?"},
        {"role": "user", "content": "I bought a used DSLR camera to start with. Nothing too expensive, but it gets the job done."},
        {"role": "assistant", "content": "Smart move — no need to spend a fortune when you're starting out. So, have you been following the news lately?"},
        {"role": "user", "content": "A bit. Did you hear about the new park they're building downtown? It's supposed to be huge."},
        {"role": "assistant", "content": "Yes! I'm so excited about it. It'll be nice to have more green space in the city. We should have a picnic there when it opens."},
        {"role": "user", "content": "That sounds fun! Speaking of which, are you going to Sarah's party this Saturday?"},
        {"role": "assistant", "content": "I wouldn't miss it! Sarah always throws the best parties. I heard she's doing a barbecue this time. Are you bringing anything?"},
        {"role": "user", "content": "I was thinking of bringing some homemade cookies. My baking skills have improved a lot recently."},
        {"role": "assistant", "content": "Homemade cookies? You're going to be everyone's favorite guest! Save one for me before they all disappear."},
        {"role": "user", "content": "Haha, I'll save two for you! Anyway, I should get going. It was really great catching up with you."},
        {"role": "assistant", "content": "You too! Let's not wait so long to catch up next time. See you at Sarah's party!"},
        {"role": "user", "content": "Definitely! See you Saturday!"},
    ],
    "travel": [
        {"role": "assistant", "content": "Welcome! Planning a trip? Let's practice talking about travel and tourist spots!"},
        {"role": "user", "content": "Hi! Yes, I'm planning a trip to Beijing next month. Have you ever been there?"},
        {"role": "assistant", "content": "Beijing is amazing! I visited two years ago. Are you going for business or vacation?"},
        {"role": "user", "content": "Pure vacation! I have a week there. What are the must-see places you'd recommend?"},
        {"role": "assistant", "content": "You absolutely must see the Great Wall. Go to the Mutianyu section — it's less crowded than Badaling and the views are stunning."},
        {"role": "user", "content": "Mutianyu, got it. How do I get there from the city center?"},
        {"role": "assistant", "content": "You can take a direct bus from Dongzhimen station. It takes about 1.5 hours. I'd recommend going early in the morning to avoid the heat and crowds."},
        {"role": "user", "content": "Good tip! What about the Forbidden City? Is it worth visiting?"},
        {"role": "assistant", "content": "Definitely! But you need to book tickets online in advance — they sell out fast. Give yourself at least half a day to explore it properly."},
        {"role": "user", "content": "I'll book those tickets tonight. What about food? I've heard Beijing duck is legendary."},
        {"role": "assistant", "content": "You have to try it! There's a famous restaurant called Quanjude that's been serving Beijing duck for over 150 years. But go hungry — it's a feast."},
        {"role": "user", "content": "My mouth is watering already! Is the public transportation easy to use there?"},
        {"role": "assistant", "content": "Very easy. The subway system is extensive and all signs are in English. Get a transportation card at any station — it's much more convenient than buying single tickets."},
        {"role": "user", "content": "Perfect. Do most people speak English, or should I learn some basic Mandarin phrases?"},
        {"role": "assistant", "content": "In tourist areas, many people speak some English. But learning a few phrases like 'ni hao' (hello) and 'xie xie' (thank you) will go a long way with locals."},
        {"role": "user", "content": "That's great advice. One more thing — what's the weather like in October?"},
        {"role": "assistant", "content": "October is one of the best months to visit! Cool and comfortable, around 10-20°C. Bring a light jacket for the evenings. And the autumn leaves are beautiful."},
        {"role": "user", "content": "Wonderful! I can't wait. Thanks for all the helpful tips!"},
    ],
    "workplace": [
        {"role": "assistant", "content": "Hi! Let's practice professional conversations for work, like meetings or emails!"},
        {"role": "user", "content": "Good morning! Do you have a moment to discuss the quarterly report? I had some questions about the data."},
        {"role": "assistant", "content": "Good morning! Of course, I have about 15 minutes before my next meeting. What specific questions do you have?"},
        {"role": "user", "content": "The sales figures for Q2 seem lower than expected. Did we account for the seasonal dip that usually happens in April?"},
        {"role": "assistant", "content": "Good catch. Yes, we factored in a 5% seasonal dip, but the actual drop was closer to 8%. The marketing team thinks the new competitor's launch affected us."},
        {"role": "user", "content": "That makes sense. I've also noticed the customer retention numbers are down. Should we bring this up in the team meeting?"},
        {"role": "assistant", "content": "Absolutely. I'll add it to the agenda for Thursday's meeting. Could you prepare a brief summary of the retention trends from the past six months?"},
        {"role": "user", "content": "I'll have it ready by Wednesday afternoon. Would you prefer a PowerPoint or a written report?"},
        {"role": "assistant", "content": "A concise written report would be better — bullet points are fine. The team prefers to discuss rather than sit through slides."},
        {"role": "user", "content": "Understood. Also, the client from the Johnson account emailed this morning. They want to extend the contract."},
        {"role": "assistant", "content": "That's great news! The Johnson account is one of our biggest. When do they want to meet to discuss the extension?"},
        {"role": "user", "content": "They suggested next Tuesday at 10 AM. Should I confirm and book the conference room?"},
        {"role": "assistant", "content": "Yes, please. Book the large conference room on the 5th floor and order some catering — coffee and pastries at least. Let's make a good impression."},
        {"role": "user", "content": "Will do. By the way, the new intern starts next week. Who's going to handle their onboarding?"},
        {"role": "assistant", "content": "I think Sarah from HR is managing the general orientation, but for team-specific training, could you take the lead? You were an intern once too."},
        {"role": "user", "content": "I'd be happy to. I'll prepare a training schedule and share it with you by Friday. Anything specific you want covered?"},
        {"role": "assistant", "content": "Make sure they understand our project management workflow and the code review process. Those are the two things new hires usually struggle with."},
        {"role": "user", "content": "Got it. I'll include hands-on exercises for both. Thanks for your time!"},
        {"role": "assistant", "content": "Thank you for the update. Great work on staying on top of everything. See you at the team meeting Thursday."},
        {"role": "user", "content": "See you then! I'll send the retention report before the meeting."},
    ],
    "service": [
        {"role": "assistant", "content": "Hello! Need help practicing talking to staff at banks, post offices, or other services?"},
        {"role": "user", "content": "Hi! I'd like to open a new savings account, please."},
        {"role": "assistant", "content": "Of course! I can help you with that. Do you currently have any other accounts with our bank?"},
        {"role": "user", "content": "Yes, I have a checking account here already. I want to start putting some money aside each month."},
        {"role": "assistant", "content": "That's a smart financial habit! Our savings accounts offer 2.5% annual interest. There's no minimum balance and no monthly fees."},
        {"role": "user", "content": "2.5% sounds reasonable. Is there a limit on how many times I can withdraw money per month?"},
        {"role": "assistant", "content": "You can make up to six withdrawals per month without any fees. After that, there's a small $3 fee per withdrawal. Most people find six is plenty for savings."},
        {"role": "user", "content": "That works for me. What documents do I need to open the account?"},
        {"role": "assistant", "content": "Since you're already a customer, I just need your ID and your existing account number. It should only take about 10 minutes to set up."},
        {"role": "user", "content": "Great, here's my ID. How do I transfer money from my checking to the savings account each month?"},
        {"role": "assistant", "content": "You can set up an automatic transfer through our mobile app. Just choose the amount and the date you want it to transfer each month."},
        {"role": "user", "content": "Perfect. One more question — I also need to mail a package internationally. Is there a post office nearby?"},
        {"role": "assistant", "content": "Yes, there's a post office two blocks south of here, right next to the pharmacy. They close at 5 PM on weekdays."},
        {"role": "user", "content": "Thanks! Do you happen to know the rates for international shipping? I'm sending a small box to Canada."},
        {"role": "assistant", "content": "For a small box to Canada, it should be around $15-25 depending on the weight. They have flat-rate boxes too, which can be cheaper if your items are heavy."},
        {"role": "user", "content": "Good to know. I'll head over there after we finish setting up the account. How long until I get my savings account card?"},
        {"role": "assistant", "content": "You'll receive your new card in the mail within 5-7 business days. In the meantime, you can access your savings through the mobile app."},
        {"role": "user", "content": "Excellent. Let's get started with the account opening then!"},
    ],
    "phone_chat": [
        {"role": "assistant", "content": "Hi! Let's practice phone or WeChat conversations, like making plans or catching up!"},
        {"role": "user", "content": "Hello? Can you hear me okay? The reception is a bit spotty here."},
        {"role": "assistant", "content": "I can hear you! It's a little fuzzy but it's fine. What's up? It's been ages since we last talked!"},
        {"role": "user", "content": "I know, I'm sorry! Life has been crazy busy. I wanted to see if you're free this weekend to hang out."},
        {"role": "assistant", "content": "This weekend? Let me check... Saturday is pretty open. What did you have in mind?"},
        {"role": "user", "content": "There's a new ramen place that opened near downtown. I thought we could try it, and then maybe catch a movie?"},
        {"role": "assistant", "content": "Ooh, ramen sounds amazing! I've been craving good noodles. What time were you thinking?"},
        {"role": "user", "content": "How about we meet at 12:30? That way we beat the lunch rush."},
        {"role": "assistant", "content": "12:30 works for me. Oh wait, I just remembered — I have a dentist appointment at 3 PM. Can we do an early lunch at 11:30 instead?"},
        {"role": "user", "content": "11:30 is fine. We can do ramen and then you can head to your appointment. The movie can wait for another day."},
        {"role": "assistant", "content": "Perfect! Thanks for being flexible. How's the new job going, by the way? Last time we talked you were just starting."},
        {"role": "user", "content": "It's going really well! The team is great and I'm learning a ton. The commute is the only downside — it takes almost an hour."},
        {"role": "assistant", "content": "An hour each way? Ouch. Are you driving or taking the train?"},
        {"role": "user", "content": "I take the train so I can read or listen to podcasts. It's not so bad once you get used to it."},
        {"role": "assistant", "content": "That's a good way to make use of the time. What podcasts are you into these days?"},
        {"role": "user", "content": "Mostly true crime and science podcasts. I'm hooked on one called 'Science Vs' — it debunks myths with actual research."},
        {"role": "assistant", "content": "That sounds fascinating! I'll have to check it out. Anyway, I should probably go — my battery is at 5% and I forgot my charger."},
        {"role": "user", "content": "Uh oh, charge that phone! I'll text you the ramen place address. See you Saturday at 11:30!"},
        {"role": "assistant", "content": "Sounds like a plan! Can't wait to catch up properly. Bye for now!"},
        {"role": "user", "content": "Bye! Don't forget to charge your phone!"},
    ],
    "hobbies": [
        {"role": "assistant", "content": "Hey! What do you like to do in your free time? Let's chat about hobbies!"},
        {"role": "user", "content": "Hey! I recently got into watercolor painting. I'm still a beginner but I find it really relaxing."},
        {"role": "assistant", "content": "Watercolor painting! That's so cool. What do you like to paint? Landscapes, flowers, abstract stuff?"},
        {"role": "user", "content": "Mostly flowers and nature scenes. They're forgiving for beginners since you can be a bit loose with the colors."},
        {"role": "assistant", "content": "That's such a good point. I tried acrylic painting once and it was... not great. The colors got muddy really fast."},
        {"role": "user", "content": "Acrylics dry so fast! That's actually why I switched to watercolors — you have more time to play with the paint."},
        {"role": "assistant", "content": "Maybe I should give watercolors a try then. Do you follow any tutorials or are you self-taught?"},
        {"role": "user", "content": "I follow some artists on YouTube. There's a channel called 'Let's Make Art' that has great beginner tutorials."},
        {"role": "assistant", "content": "I'll check that out! My main hobby is playing video games. I know it's not as artistic, but I love the storytelling in modern games."},
        {"role": "user", "content": "Hey, video games are totally a valid hobby! What kind of games do you play?"},
        {"role": "assistant", "content": "Mostly RPGs and adventure games. I just finished 'The Legend of Zelda: Tears of the Kingdom.' It was incredible — over 100 hours of gameplay."},
        {"role": "user", "content": "100 hours?! That's serious dedication. I've heard amazing things about that game. Is it worth buying a Switch for?"},
        {"role": "assistant", "content": "Honestly, yes. Between Zelda, Mario, and all the indie games, the Switch has an amazing library. Plus you can play on the go."},
        {"role": "user", "content": "You're making a strong case! Do you play any multiplayer games? We could play something together sometime."},
        {"role": "assistant", "content": "I do! I play 'Stardew Valley' and 'Mario Kart' online. Stardew is super chill — you run a farm and build relationships with villagers."},
        {"role": "user", "content": "I love Stardew Valley! I have it on PC. We should start a co-op farm together!"},
        {"role": "assistant", "content": "Yes! That would be so fun! Let's set it up this weekend. Fair warning: I'm terrible at fishing in that game."},
        {"role": "user", "content": "Haha, fishing is hard! Don't worry, I'll handle the fish while you handle the crops. Teamwork!"},
        {"role": "assistant", "content": "Deal! This is the start of a beautiful virtual farming partnership. Let's connect on Discord this weekend and get it set up."},
        {"role": "user", "content": "Sounds perfect! I'll message you my Discord username. Looking forward to it!"},
    ],
    "transport": [
        {"role": "assistant", "content": "Hi! Let's practice talking about airports, trains, or commuting!"},
        {"role": "user", "content": "Excuse me, I need to check in for my flight to Shanghai. Where is the check-in counter for China Eastern?"},
        {"role": "assistant", "content": "China Eastern is at counters 24 to 30, right over there in Terminal B. Do you have your booking confirmation ready?"},
        {"role": "user", "content": "Yes, I have it on my phone. Is there a self-check-in kiosk I can use instead?"},
        {"role": "assistant", "content": "Yes, there are self-service kiosks right before the counters. Just scan your passport and it'll print your boarding pass and baggage tags."},
        {"role": "user", "content": "Great, thanks! How many bags can I check in?"},
        {"role": "assistant", "content": "For international flights on China Eastern, you can check in two bags up to 23 kg each. Carry-on is limited to one bag under 7 kg."},
        {"role": "user", "content": "Okay, my bags should be within the limit. What's the security checkpoint like here?"},
        {"role": "assistant", "content": "Security is just past the check-in area. Make sure you take out your laptop, liquids, and any electronics larger than a phone. The lines move pretty quickly at this time."},
        {"role": "user", "content": "Good to know. Are there any restaurants or shops after security? I have a two-hour wait."},
        {"role": "assistant", "content": "Plenty! There's a food court with Chinese and Western options, duty-free shops, and a lounge near gate 15. There's also free Wi-Fi throughout the terminal."},
        {"role": "user", "content": "Perfect. What gate is my flight leaving from?"},
        {"role": "assistant", "content": "Let me check... Flight MU510 to Shanghai is departing from gate 32. Boarding starts at 2:30 PM, about an hour before departure."},
        {"role": "user", "content": "Gate 32. Is that a long walk from security?"},
        {"role": "assistant", "content": "It's about a 10-minute walk. There's also a moving walkway and shuttle carts if you prefer not to walk."},
        {"role": "user", "content": "I'll walk — it's good to stretch before a long flight. By the way, is the flight on time today?"},
        {"role": "assistant", "content": "Yes, it's showing as on time. But I'd recommend checking the departure boards occasionally, as gates can sometimes change."},
        {"role": "user", "content": "Will do. Thanks for all the help! One last thing — where can I exchange some currency?"},
        {"role": "assistant", "content": "There's a currency exchange counter near gate 10 and ATMs throughout the terminal. The exchange counter offers better rates than the ATMs, but both are reasonable."},
        {"role": "user", "content": "Great, thanks so much for your help!"},
    ],
    "housing": [
        {"role": "assistant", "content": "Hello! Let's practice conversations about renting apartments or talking to landlords!"},
        {"role": "user", "content": "Hi! I'm interested in the apartment you listed online. The two-bedroom one on Maple Street. Is it still available?"},
        {"role": "assistant", "content": "Yes, it's still available! Several people have inquired but I haven't signed a lease yet. Would you like to schedule a viewing?"},
        {"role": "user", "content": "Yes, I'd love to see it. Would tomorrow evening work? I get off work at 6 PM."},
        {"role": "assistant", "content": "Tomorrow at 6:30 PM works for me. I'll meet you at the building entrance. The address is 452 Maple Street, apartment 3B."},
        {"role": "user", "content": "Great, I'll be there. Before that, could you tell me a bit more about the place? What's the monthly rent and what utilities are included?"},
        {"role": "assistant", "content": "The rent is $1,400 per month. Water and trash are included. Electricity, gas, and internet are separate. Tenants usually pay about $100-150 total for those."},
        {"role": "user", "content": "$1,400 seems reasonable for a two-bedroom. Is there a security deposit?"},
        {"role": "assistant", "content": "Yes, the security deposit is one month's rent, so $1,400. It's fully refundable when you move out, as long as there's no damage beyond normal wear and tear."},
        {"role": "user", "content": "That's standard. What about laundry? Is there a washer and dryer in the unit?"},
        {"role": "assistant", "content": "There's a washer and dryer hookup in the unit, but you'd need to bring your own machines. There's also a laundry room in the basement with coin-operated machines."},
        {"role": "user", "content": "Okay. How's the neighborhood? I have a car, so parking is important too."},
        {"role": "assistant", "content": "The neighborhood is very safe and quiet. There's a designated parking spot behind the building included in the rent. Street parking is also available for guests."},
        {"role": "user", "content": "That's a big plus. What's the lease term? I'm looking for something long-term."},
        {"role": "assistant", "content": "The standard lease is 12 months, but we can discuss a longer term if you're interested. After the first year, it converts to month-to-month."},
        {"role": "user", "content": "A year sounds good. Are pets allowed? I have a small cat."},
        {"role": "assistant", "content": "Cats are welcome! There's a $200 pet deposit and an additional $25 per month pet rent. Dogs under 20 pounds are also allowed."},
        {"role": "user", "content": "My cat will be happy to hear that! How soon can I move in if I decide to take it?"},
        {"role": "assistant", "content": "The apartment is vacant and ready now. If you sign the lease tomorrow after viewing, you could move in as early as this weekend."},
        {"role": "user", "content": "Perfect. I'm really interested. See you tomorrow at 6:30 PM at 452 Maple Street."},
    ],
}


def main():
    """将所有场景对话写入 JSON 文件。"""
    for scene_name, messages in dialogues.items():
        file_path = CHAT_DIR / f"{scene_name}.json"
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(messages, f, ensure_ascii=False, indent=2)
        print(f"[OK] {file_path.name} — {len(messages)} messages")

    print(f"\nDone! {len(dialogues)} scene files written.")


if __name__ == "__main__":
    main()
